-- Migration 002: Extended Schema for LiteLLM on DM8 Dameng Database

CREATE TABLE "LiteLLM_DeletedTeamTable" (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    team_id VARCHAR(255) NOT NULL,
    team_alias VARCHAR(255),
    organization_id VARCHAR(255),
    object_permission_id VARCHAR(255),
    admins CLOB,
    members CLOB,
    members_with_roles CLOB,
    metadata CLOB,
    max_budget DOUBLE,
    soft_budget DOUBLE,
    spend DOUBLE DEFAULT 0.0,
    models CLOB,
    max_parallel_requests INT,
    tpm_limit BIGINT,
    rpm_limit BIGINT,
    budget_duration VARCHAR(255),
    budget_reset_at TIMESTAMP,
    blocked BIT DEFAULT 0,
    model_spend CLOB,
    model_max_budget CLOB,
    router_settings CLOB,
    team_member_permissions CLOB,
    access_group_ids CLOB,
    policies CLOB,
    model_id INT,
    allow_team_guardrail_config BIT DEFAULT 0,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_by VARCHAR(255),
    deleted_by_api_key VARCHAR(255),
    litellm_changed_by VARCHAR(255)
);

CREATE TABLE "LiteLLM_ObjectPermissionTable" (
    object_permission_id VARCHAR(255) NOT NULL PRIMARY KEY,
    mcp_servers CLOB,
    mcp_access_groups CLOB,
    mcp_tool_permissions CLOB,
    vector_stores CLOB,
    agents CLOB,
    agent_access_groups CLOB,
    models CLOB,
    blocked_tools CLOB,
    mcp_toolsets CLOB,
    search_tools CLOB
);

CREATE TABLE "LiteLLM_MCPServerTable" (
    server_id VARCHAR(255) NOT NULL PRIMARY KEY,
    server_name VARCHAR(255),
    alias VARCHAR(255),
    description CLOB,
    instructions CLOB,
    url VARCHAR(255),
    spec_path VARCHAR(255),
    transport VARCHAR(255) DEFAULT 'sse',
    auth_type VARCHAR(255),
    credentials CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255),
    mcp_info CLOB,
    mcp_access_groups CLOB,
    allowed_tools CLOB,
    tool_name_to_display_name CLOB,
    tool_name_to_description CLOB,
    extra_headers CLOB,
    static_headers CLOB,
    env_vars CLOB,
    status VARCHAR(255) DEFAULT 'unknown',
    last_health_check TIMESTAMP,
    health_check_error CLOB,
    command VARCHAR(255),
    args CLOB,
    env CLOB,
    authorization_url VARCHAR(255),
    token_url VARCHAR(255),
    registration_url VARCHAR(255),
    oauth2_flow VARCHAR(255),
    allow_all_keys BIT DEFAULT 0,
    available_on_public_internet BIT DEFAULT 1,
    delegate_auth_to_upstream BIT DEFAULT 0,
    oauth_passthrough BIT DEFAULT 0,
    is_byok BIT DEFAULT 0,
    byok_description CLOB,
    byok_api_key_help_url VARCHAR(255),
    source_url VARCHAR(255),
    timeout DOUBLE,
    approval_status VARCHAR(255) DEFAULT 'active',
    submitted_by VARCHAR(255),
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    review_notes CLOB
);

CREATE TABLE "LiteLLM_GuardrailsTable" (
    guardrail_id VARCHAR(255) NOT NULL PRIMARY KEY,
    guardrail_name VARCHAR(255) NOT NULL UNIQUE,
    litellm_params CLOB NOT NULL,
    guardrail_info CLOB,
    team_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(255) DEFAULT 'active',
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP
);

INSERT INTO LITELLM_SCHEMA_VERSION (version, migration_name) VALUES (2, '002_extended_schema.sql');
